/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gitSidebar: [
    {
      type: 'category',
      label: 'Git',
      items: [
        {
          type: 'autogenerated',
          dirName: 'git',
        }
      ]
    }
  ],

  jdsSidebar: [
    {
      type: 'category',
      label: 'Developer Essentials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'developer-essentials',
        }
      ]
    },
    {
      type: 'category',
      label: 'JDS Procedures',
      items: [
        {
          type: 'autogenerated',
          dirName: 'jds-procedures',
        }
      ]
    },
    {
      type: 'category',
      label: 'MRC',
      items: [
        {
          type: 'autogenerated',
          dirName: 'mrc',
        }
      ]
    }
  ],
};

module.exports = sidebars;

